title: Remit documentation
email: jpwilliamsphotography@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  RabbitMQ-backed microservices supporting RPC, pubsub, automatic service discovery and scaling with no code changes.
baseurl: "/remit" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

sidebar_collections:
  - start
  - guide
  - api
  - advanced
  - change

collections:
  start:
    output: true
    permalink: /docs/getting-started/:path
    title: Getting started
  guide:
    output: true
    permalink: /docs/guide/:path
    title: Guide
  api:
    output: true
    permalink: /docs/api/:path
    title: API reference
  advanced:
    output: true
    permalink: /docs/advanced/:path
    title: Advanced
  change:
    output: true
    permalink: /changelog/:path
    title: Changelog

# Build settings
markdown: kramdown

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
